language: objective-c
rvm: 2.2
osx_image: xcode8
env:
  global:
    - IOS_SIMULATOR="iPhone SE"
matrix:
  include:
    - env: BUILD_SCHEME="SQLite iOS"
    - env: BUILD_SCHEME="SQLite Mac"
    - env: VALIDATOR_SUBSPEC="none"
    - env: VALIDATOR_SUBSPEC="standard"
    - env: VALIDATOR_SUBSPEC="standalone"
before_install:
  - gem install xcpretty --no-document
script:
  - ./run-tests.sh
after_failure:
  - find $HOME/Library/Developer/Xcode/DerivedData/ -name '*.log' -print0 | xargs -0 cat
  - cat /var/log/system.log
